spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  error:
    include-message: always

app:
  auth:
    otp-expiry-minutes: 15
  media:
    max-file-size-bytes: 26214400
    allowed-image-types: image/jpeg,image/png,image/webp
    allowed-video-types: video/mp4,video/webm
